# Generated by Django 6.0.3 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flood_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('water_level', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('displaced_people', models.IntegerField()),
                ('death_toll', models.IntegerField()),
            ],
        ),
    ]
