# Generated by Django 6.0.3 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flood_report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flood_report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
