# Generated by Django 6.0.3 on 2026-03-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_flood_report_latitude_flood_report_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flood_report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='flood_report',
            name='longitude',
        ),
    ]
